### ISSUE TITLE
$EDITOR not set

### ISSUE THREAD

**Issue by scotsgeek** [vhp/terminal_velocity#19]
On a new installation of Debian Testing (Buster) before I set an environment variable for $EDITOR, without vim installed, I installed and tried to run terminal_velocity.  It reported the following:
Traceback (most recent call last):
  File "/usr/local/bin/terminal_velocity", line 129, in <module>
    main()
  File "/usr/local/bin/terminal_velocity", line 123, in main
    exclude=args.exclude)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 442, in launch
    loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 337, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 708, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 787, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 388, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 488, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 326, in keypress
    system(self.editor + ' ' + pipes.quote(self.selected_note.abspath), self.loop)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 40, in system
    raise e
OSError: [Errno 2] No such file or directory

On installation, terminal_veloctiy should have detected the missing editor and ask the user to specify an installed editor.  For the record, I use emacs.

**Comment by vhp** [comment]
Hi Rick,

That's a unique error so thanks for pointing it out. I'd imagine the 
reason this was never thought of is because distros usually tend to have 
a default editor.

Is this on a vanilla install of Debian or have you already customized 
the system? I ask because Debian traditionally uses nano(1) as its 
default editor. The same with its derivatives like Ubuntu.

**Comment by ghost** [comment]
I haven't customized one of my systems very much and I did not remove
any $EDITOR environment variable, so I would check for the variable,
and if not defined, ask the user.

I also notice you don't create a .vtrc file containing all of your
defaults.  Only a .vtlog file.  If $EDITOR is not defined, you could
set the default to nano or vim.

If you don't know about it, your product is partially similar to a
product a friend of mine used on Windows years ago, Tornado Notes. I
have been wishing for an Open Source replacement.

Any thoughts on Encryption?

What is also on your to-do or wish list?

I wish it was written in C, but that is my preference! ;^)

Cheers!

Rick


On Sun, 2018-04-01 at 18:44 +0000, Vincent Perricone wrote:
> Hi Rick,
> 
> That's a unique error so thanks for pointing it out. I'd imagine the 
> reason this was never thought of is because distros usually tend to
> have 
> a default editor.
> 
> Is this on a vanilla install of Debian or have you already
> customized 
> the system? I ask because Debian traditionally uses nano(1) as its 
> default editor. The same with its derivatives like Ubuntu.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
RSI (Rick Stanley, Inc.)
(917) 822-7771
www.rsiny.com
Computer Systems Consulting
Linux & Open Source Specialists

**Comment by vhp** [comment]
On 04/01/2018 03:14 PM, Rick Stanley wrote:
> I haven't customized one of my systems very much and I did not remove
> any $EDITOR environment variable, so I would check for the variable,
> and if not defined, ask the user.

I verified the bug and I'll get to implementing a fix sometime soon. I'm 
quite occupied with work at the moment.

>
> I also notice you don't create a .vtrc file containing all of your
> defaults. Only a .vtlog file. If $EDITOR is not defined, you could
> set the default to nano or vim.
You're right. The defaults are kinda just in the a file and it was 
decided long ago to have users copy the file. We can generate a file 
though.

>
> If you don't know about it, your product is partially similar to a
> product a friend of mine used on Windows years ago, Tornado Notes. I
> have been wishing for an Open Source replacement.
I haven't heard of it but maybe Sean the original Author had.

>
> Any thoughts on Encryption?
This is not going to be implemented. The reason is encryption is hard 
and many peoples editors already can encrypt documents. So adding this 
extra ability doesn't add much benefit.

> What is also on your to-do or wish list?
Not sure if you have noticed but the second maintainer of the project. I 
sometimes use it but frankly seldom do anymore. I am happy to maintain 
it and fix bugs so people can use it. I think it's a pretty good and 
useful piece of software. But as for the future there's not exactly much 
planned.

How about you? What are your ideas?

I hate to sound unenthusiastic. But sometimes adding features doesn't 
make software better. It just makes it more complex and more prone to bugs.

>
> I wish it was written in C, but that is my preference! ;^)
It's Python so deep down it is C anyway. :) I think it's just to hard to 
work on if it were something like C. There's a lot of benefit to Python.

>
> Cheers!
>
> Rick
>
